server:
  port: 80

spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/gyumin
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  data:
    web:
      pageable:
        one-indexed-parameters: true
        default-page-size: 5

logging:
  level:
    org.hibernate.type.descriptor.sql: trace